# Generated by Django 5.1.3 on 2025-02-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa'),
        ),
    ]
