# Generated by Django 5.1.3 on 2024-11-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaFFA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPagamento', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipoPagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaFFA.pagamento'),
        ),
    ]
