# Generated by Django 5.1.3 on 2024-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaFFA', '0003_tipocategoria_transacao_categorianome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoConta', models.CharField(max_length=30)),
            ],
        ),
    ]
