# Generated by Django 5.1.3 on 2024-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaFFA', '0005_remove_contabancaria_tipo_contabancaria_tipoconta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
    ]
