# Generated by Django 5.1.3 on 2024-12-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaFFA', '0006_tipocontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='tipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sistemaFFA.tipocontato'),
            preserve_default=False
        ),
    ]
