# Generated by Django 5.1.3 on 2025-02-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaFFA', '0010_tipotransacao_transacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável'), ('imposto', 'Imposto'), ('rendimento', 'Rendimento')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TipoCategoria',
        ),
    ]
